name: py311_overlappingassays
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit
  - jupyter
  - scipy
  - scikit-learn
  - psycopg2
  - ipython-sql
  - matplotlib
  - sqlalchemy=1.4
  - pandas
  